#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use apps_desktop_tauri::commands;

fn main() {
    let builder = tauri::Builder::default().invoke_handler(tauri::generate_handler![
        commands::vault_init,
        commands::vault_open,
        commands::trust_identity_start,
        commands::trust_identity_complete,
        commands::trust_device_enroll,
        commands::trust_device_enroll_signing_key,
        commands::trust_device_verify_chain,
        commands::trust_device_list,
        commands::trust_device_signing_key_status,
        commands::trust_device_signing_key_delete,
        commands::trust_device_signing_key_rotate,
        commands::trust_provider_add,
        commands::trust_provider_disable,
        commands::trust_provider_list,
        commands::trust_provider_discover,
        commands::trust_policy_set,
        commands::trust_policy_set_tenant_template,
        commands::vault_lock_status,
        commands::vault_unlock,
        commands::vault_lock,
        commands::vault_encryption_status,
        commands::vault_encryption_enable,
        commands::vault_encryption_migrate,
        commands::vault_recovery_status,
        commands::vault_recovery_generate,
        commands::vault_recovery_verify,
        commands::vault_recovery_escrow_status,
        commands::vault_recovery_escrow_enable,
        commands::vault_recovery_escrow_rotate,
        commands::vault_recovery_escrow_restore,
        commands::vault_recovery_escrow_provider_add,
        commands::vault_recovery_escrow_provider_list,
        commands::vault_recovery_escrow_rotate_all,
        commands::ingest_scan_folder,
        commands::ingest_inbox_start,
        commands::ingest_inbox_stop,
        commands::search_query,
        commands::locator_resolve,
        commands::export_bundle,
        commands::verify_bundle,
        commands::ask_question,
        commands::events_list,
        commands::jobs_list,
        commands::sync_status,
        commands::sync_push,
        commands::sync_pull,
        commands::sync_merge_preview,
        commands::lineage_query,
        commands::lineage_query_v2,
        commands::lineage_overlay_add,
        commands::lineage_overlay_remove,
        commands::lineage_overlay_list,
        commands::lineage_lock_acquire,
        commands::lineage_lock_release,
        commands::lineage_lock_status,
        commands::lineage_role_grant,
        commands::lineage_role_revoke,
        commands::lineage_role_list,
        commands::lineage_policy_add,
        commands::lineage_policy_bind,
        commands::lineage_policy_list,
        commands::lineage_lock_acquire_scope,
    ]);

    builder
        .run(tauri::generate_context!())
        .expect("failed to run tauri app");
}
